### ISSUE TITLE
Allow running from current directory

### ISSUE THREAD

**Issue by mleonhard** [AvaterClasher/mextron#1]
Hi Soumyadip,
Thanks for sharing Mextron.  I'm trying to run it in dev mode.
```
user@Users-MBP www-mleonhard-com % mextron dev   
error: the following required arguments were not provided:
  <INPUT_DIR>

Usage: mextron dev <INPUT_DIR>

For more information, try '--help'.
user@Users-MBP www-mleonhard-com % mextron dev .

Sorry, you cannot use current directory as input directory as output is written to it!
```

This is confusing.  If I run it from `~/`, will it write files into `~/`?  I do not want that.  I want to `cd` into the project's directory and run `mextron dev`.  I want it to write the generated site into `_site/` inside the project's directory.  I have several sites and I want to keep their generated files separate.

How about updating the tool?
1. Allow running from the current directory, without specifying the directory path
2. Write the site into `_site/` inside the project's directory
3. Add a note about this to the README.md file

Sincerely,
Michael

**Comment by AvaterClasher** [comment]
Hello @mleonhard, 

First of all thank you for trying out Mextron. Also how did you find this project ?

**Comment by AvaterClasher** [comment]
@mleonhard 
Thank you for creating this issue the latest commit has addressed and solved. This issue this has been added in the projects's README as well. 
Thank You 🦀
